# Generated by Django 6.1 on 2026-08-22 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the display order (1-6, etc.)')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slide_deck', models.FileField(blank=True, help_text='Upload the .ppt/.pptx file for this module', null=True, upload_to='module_slides/')),
                ('video', models.FileField(blank=True, help_text='Leave empty for now — reserved for when video content is added', null=True, upload_to='module_videos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='modules.module')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='accounts.patient')),
            ],
            options={
                'unique_together': {('patient', 'module')},
            },
        ),
    ]
